# Generated by Django 3.2.9 on 2021-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=80)),
                ('Last_name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=80)),
                ('Phone_Number', models.IntegerField()),
                ('Department', models.CharField(max_length=80)),
                ('Level', models.IntegerField()),
            ],
        ),
    ]
